services:

  cms.admin.halper:
      class: Youshido\CMSBundle\Service\AdminHelper
      calls:
        - [ setContainer, [ @service_container ] ]

  cms.attribute:
      class: Youshido\CMSBundle\Service\AttributeService
      calls:
        - [ setContainer, [ @service_container ] ]

  cms.structure:
      class: Youshido\CMSBundle\Service\StructureService
      calls:
        - [ setContainer, [ @service_container ] ]

  cms.provider.page:
      class: Youshido\CMSBundle\Service\Provider\PageProvider
      calls:
            - [ setContainer, [ @service_container ] ]